stages:
  Status:
    actions:
    - type: liquibase
      command: status


  Update:
    actions:
    - type: liquibase
      # if: "${LBCOMMAND} == update"
      command: update

endStage:
  actions:
  - type: liquibase
    command: history